Setting "Opacity" as an attribute in <layer-> tag #issue667new
Maps4HTML/Web-Map-Custom-Element pull request #733
Opened 2023-01-30 18:57 UTC by Jacky0299

closes #667

2023-01-31 17:10 UTC, prushforth reviewed
Although layerAttribute is a pretty good name, unless you are planning to test the other attributes of the layer element in this same file, I would focus the name the test layerOpacityAttribute.test.js, to be clear.

2023-01-31 17:12 UTC, prushforth commented on test/e2e/layers/layerAttribute.test.js
> +    if (opacity_attribute_value == null){
I believe you want to use "===" mostly in JavaScript.  I believe that you can re-phrase the logic of this as:

```javascript
if (opacity_attribute_value) {
...
}

2023-01-31 17:14 UTC, prushforth commented on test/e2e/layers/layerAttribute.test.js
> +    }
I prefer to (try to) maintain one style of code block

Generally I prefer

```javascript
if (something) {
...
} else if (something_else) {
...
} else {
...
}

2023-01-31 17:18 UTC, prushforth requested changes
Functions very well, AFAICT! Please make the style changes suggested!  We can merge after that.

I think we could add an opacity attribute to the \<map-extent> element now and you will be better able to understand what the impacts are, although we don't have a \<map-extent> custom element yet (soon!).

2023-01-31 19:03 UTC, AliyanH commented
Works very nicely! Since a new attribute has been added to the layer, you should also update the web-map-doc to document the change (https://maps4html.org/web-map-doc/docs/layers/layer/#attributes).

2023-01-31 19:31 UTC, prushforth approved these changes

2023-02-01 15:57 UTC, AliyanH commented
Looks good @Jacky0299! Feel free to "Squash and merge" when ready. Good work! You can also merge the [documentation](https://github.com/Maps4HTML/web-map-doc/pull/100), once this is merged.

2023-02-01 16:47 UTC, merged